language: cpp

os: linux

matrix:
  include:
    - addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
           - clang++-7.0
      env:
         - MATRIX_EVAL="CC=clang-7.0 && CXX=clang++-7.0"

    - addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
           - g++-8
      env:
         - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"

before_install:
  eval ${MATRIX_EVAL}

install: 
  - git clone https://github.com/mirmik/igris igris/
  - cd igris
  - cmake .
  - make
  - sudo make install
  - cd ..
  
script:
  - echo "SCRIPT"
  - pwd
  - ls

  - cmake --version
  - cmake CMakeLists.txt
  - make
  - sudo make install
  - ./nos_test
  - make test
