language: cpp

os: linux

matrix:
  include:
    - addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
           - g++-8
      env:
         - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"

before_install:
  eval ${MATRIX_EVAL}
  
script:
  - echo "SCRIPT"
  - pwd
  - ls

  - cmake --version
  - cmake CMakeLists.txt
  - make
  - sudo make install
  - ./nos_test
  - make test
